name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Azure Container Registry Build
      uses: Azure/acr-build@v1
      with:
    # Service Principal with Contributor role on the ACR
        service_principal: ${{ secrets.principal }}
    # Service Principal password
        service_principal_password: ${{ secrets.password }}
    # Azure Container Registry tenant
        tenant: ${{ secrets.tenant }}
      # The name of the ACR, minus the .azurecr.io
        registry: cataclysmshipyard
      # Repository to use
        repository: blog
    # Docker image name
        image: blog
    # The folder in the Github repo that holds the source
        folder: .
